name: potato_timer
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # to show snackbar on the screen
  another_flushbar: ^1.10.29
  audioplayers: ^5.1.0
  auto_size_text: ^3.0.0

  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2

  dartz: ^0.10.1
  drift: ^2.11.0

  flutter_screenutil: 5.8.4
  flutter_spinkit: ^5.2.0
  flutter_mobx: ^2.0.6+5
  freezed_annotation: ^2.2.0

  gap: ^3.0.1
  get_it: ^7.6.0
  google_fonts: ^5.1.0

  injectable: ^2.1.1

  mobx: ^2.2.0

  path: ^1.8.3
  path_provider: ^2.1.0
  provider: ^6.0.5

  rxdart: ^0.27.7
  sqlite3_flutter_libs: ^0.5.15

dev_dependencies:
  build_runner: ^2.1.2
  drift_dev: ^2.11.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.3.1
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/